version: 'latest'
services:
  mariadb:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    ports:
      - 3308:3306
    environment:
      MARIADB_USER: root
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql 

